export const languageIcons: Record<string, string> = {
  markdown: 'devicon:markdown',
  mdx: 'devicon:markdown',
  html: 'devicon:html5',
  css: 'devicon:css3',
  javascript: 'devicon:javascript',
  js: 'devicon:javascript',
  typescript: 'devicon:typescript',
  ts: 'devicon:typescript',
  python: 'devicon:python',
  py: 'devicon:python',
  dart: 'devicon:dart',
  rust: 'catppuccin:rust',
  rs: 'catppuccin:rust',
  npm: 'devicon:npm',
  npx: 'devicon:npm',
  yarn: 'devicon:yarn',
  pnpm: 'devicon:pnpm',
  cargo: 'catppuccin:cargo',
  bun: 'devicon:bun',
  vite: 'devicon:vite',
  'tailwind.config.js': 'devicon:tailwindcss',
  'tailwind.config.ts': 'devicon:tailwindcss',
  react: 'devicon:react',
  nextjs: 'devicon:nextjs',
  svelte: 'devicon:svelte',
  vue: 'devicon:vuejs',
  go: 'devicon:go',
  bash: 'devicon:bash',
  sh: 'devicon:bash',
  shell: 'devicon:bash',
  sql: 'devicon:azuresqldatabase',
  yaml: 'devicon:yaml',
  yml: 'devicon:yaml',
  json: 'devicon:json',
  dockerfile: 'devicon:docker',
  git: 'devicon:git',
  github: 'devicon:github',
  gitlab: 'devicon:gitlab',
  math: 'mdi:function-variant',
  latex: 'mdi:function-variant',
  mermaid: 'mdi:graph-outline',
}

export const shellLanguages = ['bash', 'sh', 'shell']
export const terminalCommands = ['npm', 'npx', 'pnpm', 'yarn', 'bun', 'cargo']
